function interfaceFlow = importInterfaceFlow(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXTERNALLIMITSFLOWS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  EXTERNALLIMITSFLOWS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ExternalLimitsFlows = importfile("D:\EERL\2019_NYISO\2019_Interface_Flow\20190101ExternalLimitsFlows.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03/08/2021 11:15:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "InterfaceName", "PointID", "FlowMWH", "PositiveLimitMWH", "NegativeLimitMWH"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["InterfaceName", "PointID"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Timestamp", "InputFormat", "MM/dd/yyyy HH:mm");

% Import the data
interfaceFlow = readtable(filename, opts);

end