function genNearestPVBus = importNearestPVBus(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  GENNEARESTPVBUS = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  GENNEARESTPVBUS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  GENNEARESTPVBUS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  genNearestPvBus = importNearestPVBus("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\NPCC140\nearest_ny_pv_bus_to_gen.xlsx", "nearest_ny_pv_bus_to_gen", [2, 211]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02/22/2021 19:02:35

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 226];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":M" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["NYISOname", "PTID", "Zone", "UnitType", "DualFuel", "FuelTypepr", "FuelTypese", "NamePlateR", "NetEnergyG", "Latitude", "Longitude", "BusName", "BusDist"];
opts.SelectedVariableNames = ["NYISOname", "PTID", "Zone", "Latitude", "Longitude", "BusName", "BusDist"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double"];

% Specify variable properties
opts = setvaropts(opts, ["NYISOname", "PTID", "Zone", "BusName"], "EmptyFieldRule", "auto");

% Import the data
genNearestPVBus = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":M" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    genNearestPVBus = [genNearestPvBus; tb]; %#ok<AGROW>
end

end