function NYCAGenThermal = importGenThermal(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NYCAGENTHERMAL = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  NYCAGENTHERMAL = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NYCAGENTHERMAL = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NYCAGenThermal = importGenThermal("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\2019_NYCA_Generators.xlsx", "2019 thermal", [2, 320]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02/20/2021 00:08:05

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = "2019 thermal";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 320];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 19);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":S" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["LineRefNo", "BillingOrganization", "NYISOname", "Zone", "PTID", "Town", "County", "State", "InServiceDate", "NamePlateRatingMW", "CRISSummerMW", "CRISWinterMW", "CapabilitySummerMW", "CapabilityWinterMW", "DualFuel", "UnitType", "FuelTypeprimary", "FuelTypesecondary", "NetEnergyGWh"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "double"];

% Specify variable properties
opts = setvaropts(opts, ["LineRefNo", "BillingOrganization", "NYISOname", "Zone", "PTID", "Town", "County", "State", "DualFuel", "UnitType", "FuelTypeprimary", "FuelTypesecondary"], "EmptyFieldRule", "auto");

% Import the data
NYCAGenThermal = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":S" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NYCAGenThermal = [NYCAGenThermal; tb]; %#ok<AGROW>
end

end