function line2NYCABus = importLineFull(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LINE2NYCABUS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LINE2NYCABUS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  line2NYCABus = importLineFull("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\NPCC140\line_with_ny_bus.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02/23/2021 11:46:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 31);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["idx", "u", "name", "bus1_idx", "bus2_idx", "Sn", "fn", "Vn1", "Vn2", "r", "x", "b", "g", "b1", "g1", "b2", "g2", "trans", "tap", "phi", "bus1_name", "bus1_area", "bus1_xcoor", "bus1_ycoor", "Var25", "bus2_name", "bus2_area", "bus2_xcoor", "bus2_ycoor", "Var30", "voltageCla"];
opts.SelectedVariableNames = ["idx", "u", "name", "bus1_idx", "bus2_idx", "Sn", "fn", "Vn1", "Vn2", "r", "x", "b", "g", "b1", "g1", "b2", "g2", "trans", "tap", "phi", "bus1_name", "bus1_area", "bus1_xcoor", "bus1_ycoor", "bus2_name", "bus2_area", "bus2_xcoor", "bus2_ycoor", "voltageCla"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "string", "categorical", "categorical", "double", "double", "string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var25", "Var30"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["idx", "u", "name", "bus1_idx", "bus2_idx", "bus1_name", "bus1_area", "Var25", "bus2_name", "bus2_area", "Var30", "voltageCla"], "EmptyFieldRule", "auto");

% Import the data
line2NYCABus = readtable(filename, opts);

end