function RTMZonalPrice = importRTMZonalPrice(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RTMZONALPRICE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RTMZONALPRICE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  RTMZonalPrice = importfile("D:\EERL\2019_NYISO\2019_RTM_LBMP_Zonal\20190101realtime_zone.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03/08/2021 11:06:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "Name", "PTID", "LBMPMWHr", "MarginalCostLossesMWHr", "MarginalCostCongestionMWHr"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Name", "PTID"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeStamp", "InputFormat", "MM/dd/yyyy HH:mm:ss");

% Import the data
RTMZonalPrice = readtable(filename, opts);

end