function nearestBus2Gen = importNearestBus(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NEARESTBUS2GEN = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  NEARESTBUS2GEN = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  nearestBus2Gen = importNearestBus("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\NPCC140\nearest_ny_pv_bus_to_gen.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02/23/2021 11:31:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["NYISOname", "PTID", "Zone", "UnitType", "DualFuel", "FuelTypepr", "FuelTypese", "NamePlateR", "NetEnergyG", "Latitude", "Longitude", "BusName", "BusDist"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["NYISOname", "PTID", "Zone", "UnitType", "DualFuel", "FuelTypepr", "FuelTypese", "BusName"], "EmptyFieldRule", "auto");

% Import the data
nearestBus2Gen = readtable(filename, opts);

end