function externalEnergy = importTotalEnergy(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DAMENERGYREP = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DAMENERGYREP = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  externalEnergy = importExternalEnergy("D:\EERL\2019_NYISO\2019_Daily_Energy\20190101DAM_energy_rep.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03/11/2021 01:41:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, 25];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 71);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "TotalLoadOffered", "TotalLoadScheduled", "GenerationBidsOffered", "GenerationBidsScheduled", "ImportsOffered", "ImportsScheduled", "ExportsOffered", "ExportsScheduled", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "NetImportsDNIOH", "NetImportsDNIHQ", "NetImportsDNIPJM", "NetImportsDNINPX", "NetImportsNYISO", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "Var64", "Var65", "Var66", "Var67", "Var68", "Var69", "Var70", "Var71"];
opts.SelectedVariableNames = ["TimeStamp", "TotalLoadOffered", "TotalLoadScheduled", "GenerationBidsOffered", "GenerationBidsScheduled", "ImportsOffered", "ImportsScheduled", "ExportsOffered", "ExportsScheduled", "NetImportsDNIOH", "NetImportsDNIHQ", "NetImportsDNIPJM", "NetImportsDNINPX", "NetImportsNYISO"];
opts.VariableTypes = ["datetime", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "Var64", "Var65", "Var66", "Var67", "Var68", "Var69", "Var70", "Var71"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "Var64", "Var65", "Var66", "Var67", "Var68", "Var69", "Var70", "Var71"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeStamp", "InputFormat", "MM/dd/yyyy HH:mm");

% Import the data
externalEnergy = readtable(filename, opts);

end