function genParam = importGenParam(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GENPARAM = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  GENPARAM = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  genParam = importGenParam("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\genParam.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02/22/2021 23:36:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["NYISOName", "PTID", "UnitType", "FuelType", "Zone", "NamePlateRatingMW", "maxPower", "minPower", "maxRampAgc", "maxRamp10", "maxRamp30", "maxRamp60", "HeatRateLM_1", "HeatRateLM_2", "HeatRateLMR2"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["NYISOName", "PTID", "UnitType", "FuelType", "Zone"], "EmptyFieldRule", "auto");

% Import the data
genParam = readtable(filename, opts);

end