function loadForecast = importLoadForecast(filename, dataLines)
%IMPORTFILE Import data from a text file
%  loadForecast = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  loadForecast = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  loadForecast = importLoadForecast("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\NYISO_DAM_Load_2019.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03/08/2021 10:57:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "ZoneName", "DAMForecastLoad", "GMTStartHour"];
opts.SelectedVariableNames = ["TimeStamp", "ZoneName", "DAMForecastLoad"];
opts.VariableTypes = ["datetime", "categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ZoneName", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeStamp", "InputFormat", "MM/dd/yyyy HH:mm");

% Import the data
loadForecast = readtable(filename, opts);

end