function actIntegLoad = importActIntegLoad(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACTINTEGLOAD = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ACTINTEGLOAD = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  actIntegLoad = importfile("D:\EERL\2019_NYISO\2019_RTM_Integrated_Actual_Load\20190101palIntegrated.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03/08/2021 11:01:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "Var2", "Name", "PTID", "IntegratedLoad"];
opts.SelectedVariableNames = ["TimeStamp", "Name", "PTID", "IntegratedLoad"];
opts.VariableTypes = ["datetime", "string", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Name", "PTID"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeStamp", "InputFormat", "MM/dd/yyyy HH:mm:ss");

% Import the data
actIntegLoad = readtable(filename, opts);

end