function NYSSubstations = importNYSSubstations(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NYSSUBSTATIONS = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  NYSSUBSTATIONS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NYSSUBSTATIONS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NYSSubstations = importfile("D:\EERL\NY-Simple-Net\NY-Simple-Net-main\Data\Transmission\NYS_Substations.xlsx", "Sheet1", [2, 2778]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01/26/2021 10:21:40

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2778];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 19);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":S" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["X", "Y", "ObjectID", "ID", "Name", "City", "State", "Zip", "Type", "Status", "County", "CountyFIPs", "Latitude", "Longitude", "Lines", "MaxVolt", "MinVolt", "MaxInfer", "MinInfer"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "string", "string", "categorical", "double", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Name", "City"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ObjectID", "ID", "Name", "City", "State", "Type", "Status", "County", "MaxInfer", "MinInfer"], "EmptyFieldRule", "auto");

% Import the data
NYSSubstations = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":S" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NYSSubstations = [NYSSubstations; tb]; %#ok<AGROW>
end

%% Change case of the name
NYSSubstations.Name = lower(NYSSubstations.Name);
NYSSubstations.Name = 


end